import { signal } from "@preact/signals"
import Head from 'next/head'
import Image from 'next/image'

const todos = signal([
  { text: "Buy groceries" },
  { text: "Walk the dog" },
]);

export default function Home() {
  const addTodo = event => {
    event.preventDefault()
    const form = event.currentTarget
    const data = new FormData(form)
    const text = data.get('todo')
    if (!text || text === '') return
    todos.value = [...todos.value, { text }]
    form.reset()
  }
  const removeTodo = index => {
    const value = [...todos.value]
    value.splice(index, 1)
    todos.value = value
  }
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>hello</div>
      <ol>{
        todos.value.map((todo, index) =>
          <li>
            <span>{todo.text}</span>
            <button onClick={() => removeTodo(index)}>X</button>
          </li>
        )
      }</ol>
      <form onSubmit={addTodo}>
        <input type="text" name="todo"></input>
        <button type="submit">ADD</button>
      </form>
    </div>
  )
}
